name: Reusable Workflow

on:
  workflow_call:

jobs:

  ru2-job1:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Write something to log
        run: |
          echo "This is the workflow which is being called"
          
      - name: Check cwd
        run: |
             pwd
             id
             docker ps
             ls -al /home/runner/work/
             #cd /home/runner/work/mcs-called
             #chmod 777 ./scripts/build.sh
             #sh ./scripts/build.sh
        
