name: Reusable Workflow

on:
  workflow_call:

jobs:

  ru2-job1:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Write something to log
        run: |
          echo "I am Reuseable Workflow - running from calledRepo main branch"
          
      - name: Check cwd
        run: |
             pwd
             id
             
      - name: Change permission
        run: chmod 777 ./scripts/build.sh
          
      - name: Run a bash script
        run: sh ./scripts/build.sh
      shell: bash
        
